name: Quality

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: "1.86"

jobs:
  quality:
    name: Run Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Configure Git to use HTTPS with token
        run: |
          git config --global url."https://${{ secrets.WILLBANK_PLATFORMS_PERSONAL_ACCESS_TOKEN }}:@github.com/".insteadOf "https://github.com/"

      - uses: will-bank/rust-setup-action@v1.80
        with:
          toolchain: 1.86.0
          components: clippy, rustfmt
      
      - name: Lint
        run: make lint

      - name: Test and Coverage
        run: make test_ci
